import SidebarApp from '@/app/dashboard/components/sidebar';
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app'
};

export default function DashboardLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <SidebarApp>
      {children}
    </SidebarApp>
  );
}
